CREATE DATABASE quan_ly_sinh_vien;
USE quan_ly_sinh_vien;

-- 1. TaiKhoan
CREATE TABLE TaiKhoan (
    ID_TaiKhoan INT AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(50) UNIQUE NOT NULL,
    MatKhau VARCHAR(255) NOT NULL,
    VaiTro ENUM('admin','sinhvien','thisinh') NOT NULL,
    TrangThai BOOLEAN DEFAULT TRUE
);

-- 2. Khoa
CREATE TABLE Khoa (
    MaKhoa VARCHAR(2) PRIMARY KEY,
    TenKhoa VARCHAR(100) UNIQUE NOT NULL
);

-- 3. Nganh
CREATE TABLE Nganh (
    MaNganh VARCHAR(4) PRIMARY KEY,
    TenNganh VARCHAR(100) NOT NULL,
    MaKhoa VARCHAR(2),
    FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa)
);

-- 4. Lop
CREATE TABLE Lop (
    MaLop VARCHAR(11) PRIMARY KEY,
    TenLop VARCHAR(100) UNIQUE NOT NULL,
    MaNganh VARCHAR(4),
    FOREIGN KEY (MaNganh) REFERENCES Nganh(MaNganh)
);

-- 5. MonHoc
CREATE TABLE MonHoc (
    MaMH VARCHAR(7) PRIMARY KEY,
    TenMH VARCHAR(100) NOT NULL,
    SoTinChi INT NOT NULL,
    CHECK (SoTinChi > 0)
);

-- 6. QuanTri
CREATE TABLE QuanTri (
    MaAdmin INT AUTO_INCREMENT PRIMARY KEY,
    HoTen VARCHAR(100),
    ID_TaiKhoan INT UNIQUE,
    FOREIGN KEY (ID_TaiKhoan) REFERENCES TaiKhoan(ID_TaiKhoan)
);

-- 7. HSO_XETTUYEN
CREATE TABLE HSO_XETTUYEN (
    MaHSO INT AUTO_INCREMENT PRIMARY KEY,
    ID_TaiKhoan INT UNIQUE,
    HoTen VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh ENUM('Nam','Nữ') NOT NULL,
    CCCD VARCHAR(12) UNIQUE NOT NULL,
    SDT VARCHAR(15) UNIQUE NOT NULL,
    FOREIGN KEY (ID_TaiKhoan) REFERENCES TaiKhoan(ID_TaiKhoan)
);

-- 8. SinhVien
CREATE TABLE SinhVien (
    MaSV VARCHAR(10) PRIMARY KEY,
    HoTen VARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    ID_TaiKhoan INT UNIQUE,
    MaLop VARCHAR(11),
    MaHSO INT,
    FOREIGN KEY (ID_TaiKhoan) REFERENCES TaiKhoan(ID_TaiKhoan),
    FOREIGN KEY (MaLop) REFERENCES Lop(MaLop),
    FOREIGN KEY (MaHSO) REFERENCES HSO_XETTUYEN(MaHSO)
);

-- 9. PT_XetTuyen
CREATE TABLE PT_XetTuyen (
    MaPTXT INT AUTO_INCREMENT PRIMARY KEY,
    MaHSO INT NOT NULL,
    MaNganh VARCHAR(4) NOT NULL,
    LoaiPT ENUM('Đánh giá năng lực','Học bạ kết hợp IELTS','Điểm thi THPT') NOT NULL,
    Diem DECIMAL(4,2) NOT NULL,
    DiemIELTS DECIMAL(2,1),
    FileDGNL VARCHAR(255),
    FileHocBa VARCHAR(255),
    FileIELTS VARCHAR(255),
    TrangThai ENUM('Chờ duyệt','Trúng tuyển','Từ chối') DEFAULT 'Chờ duyệt',
    MaAdmin INT,
    FOREIGN KEY (MaHSO) REFERENCES HSO_XETTUYEN(MaHSO),
    FOREIGN KEY (MaNganh) REFERENCES Nganh(MaNganh),
    FOREIGN KEY (MaAdmin) REFERENCES QuanTri(MaAdmin)
);

-- 10. KQ_HocTap
CREATE TABLE KQ_HocTap (
    MaSV VARCHAR(10),
    MaMH VARCHAR(7),
    Diem DECIMAL(4,2) NOT NULL,
    PRIMARY KEY (MaSV, MaMH),
    FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV),
    FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH)
);

-- 11. TotNghiep
CREATE TABLE TotNghiep (
    MaSV VARCHAR(10) PRIMARY KEY,
    GPA DECIMAL(4,2) NOT NULL,
    XepLoai ENUM('Xuất sắc','Giỏi','Khá','Trung bình','Yếu') NOT NULL,
    CHECK (GPA >= 0 AND GPA <= 4.0),
    FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV)
);

-- 12. ThongBao
CREATE TABLE ThongBao (
    MaTB INT AUTO_INCREMENT PRIMARY KEY,
    NoiDung VARCHAR(255) NOT NULL,
    NgayGui DATETIME DEFAULT CURRENT_TIMESTAMP,
    MaAdmin INT,
    FOREIGN KEY (MaAdmin) REFERENCES QuanTri(MaAdmin)
);

-- 13. TB_NguoiNhan
CREATE TABLE TB_NguoiNhan (
    MaTBNN INT AUTO_INCREMENT PRIMARY KEY,
    MaTB INT NOT NULL,
    ID_TaiKhoan INT NOT NULL,
    TrangThaiDoc BOOLEAN DEFAULT FALSE,
    ThoiGianDoc DATETIME,
    FOREIGN KEY (MaTB) REFERENCES ThongBao(MaTB),
    FOREIGN KEY (ID_TaiKhoan) REFERENCES TaiKhoan(ID_TaiKhoan)
);

-- 14. ViecLamSinhVien
CREATE TABLE ViecLamSinhVien (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MaSV VARCHAR(10) NOT NULL,
    TenCongTy VARCHAR(255) NOT NULL,
    ChucVu VARCHAR(100),
    DiaChiCongTy VARCHAR(255),
    ThoiGianBatDau DATE,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV)
);

-- 15. TinNhan
CREATE TABLE TinNhan (
    MaTinNhan INT AUTO_INCREMENT PRIMARY KEY,
    ID_NguoiGui INT NOT NULL,
    ID_NguoiNhan INT,
    NoiDung VARCHAR(100) NOT NULL,
    ThoiGianGui DATETIME DEFAULT CURRENT_TIMESTAMP,
    DaDoc BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (ID_NguoiGui) REFERENCES TaiKhoan(ID_TaiKhoan),
    FOREIGN KEY (ID_NguoiNhan) REFERENCES TaiKhoan(ID_TaiKhoan)
);

-- 16. ReviewNganh
CREATE TABLE ReviewNganh (
    MaReview INT AUTO_INCREMENT PRIMARY KEY,
    MaSV VARCHAR(10) NOT NULL,
    MaNganh VARCHAR(4) NOT NULL,
    NoiDung VARCHAR(255),
    ThoiGian DATETIME DEFAULT CURRENT_TIMESTAMP,
    TrangThai ENUM('Chờ duyệt','Đã hiển thị','Vi phạm') DEFAULT 'Chờ duyệt',
    MaAdmin INT,
    FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV),
    FOREIGN KEY (MaNganh) REFERENCES Nganh(MaNganh),
    FOREIGN KEY (MaAdmin) REFERENCES QuanTri(MaAdmin)
);
--17. Tổ hợp môn
CREATE TABLE ToHopMon (
    MaToHop INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    TenToHop VARCHAR(100) NOT NULL, 
    CacMon VARCHAR(255) DEFAULT NULL        
);

-- 1. Thêm cột MaToHop vào bảng PT_XetTuyen
ALTER TABLE PT_XetTuyen 
ADD COLUMN MaToHop INT DEFAULT NULL;

-- 2. Thiết lập ràng buộc khóa ngoại
ALTER TABLE PT_XetTuyen
ADD CONSTRAINT FK_PTXT_ToHop 
FOREIGN KEY (MaToHop) REFERENCES ToHopMon(MaToHop) 
ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE ChiTietDiemHocBa (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MaPTXT INT NOT NULL,
    TenMon VARCHAR(50) NOT NULL,
    DiemMon DECIMAL(4, 2) NOT NULL,
    CONSTRAINT fk_chi_tiet_ptxt FOREIGN KEY (MaPTXT) 
        REFERENCES PT_XetTuyen(MaPTXT) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Đảm bảo cột Diem có thể nhận giá trị mặc định là 0 trước khi tính toán
ALTER TABLE PT_XetTuyen 
MODIFY COLUMN Diem DECIMAL(4, 2) DEFAULT 0.00;

CREATE TABLE Nganh_ToHop (
    MaNganh VARCHAR(4) NOT NULL,
    MaToHop INT NOT NULL,
    PRIMARY KEY (MaNganh, MaToHop),
    CONSTRAINT FK_Nganh_ToHop_Nganh FOREIGN KEY (MaNganh) 
        REFERENCES Nganh(MaNganh) ON DELETE CASCADE,
    CONSTRAINT FK_Nganh_ToHop_ToHop FOREIGN KEY (MaToHop) 
        REFERENCES ToHopMon(MaToHop) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;