-- =============================================
-- FULL MYSQL SCHEMA GENERATED FROM FLASK MODELS
-- =============================================
CREATE DATABASE IF NOT EXISTS quanly_sinhvien
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE quanly_sinhvien;

-- 1. TAI KHOAN
CREATE TABLE TaiKhoan (
    ID_TaiKhoan INT AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    VaiTro ENUM('admin','sinhvien','thisinh') NOT NULL,
    TrangThai BOOLEAN DEFAULT TRUE
);

-- 2. KHOA
CREATE TABLE Khoa (
    MaKhoa VARCHAR(2) PRIMARY KEY,
    TenKhoa VARCHAR(100) NOT NULL UNIQUE
);

-- 3. NGANH
CREATE TABLE Nganh (
    MaNganh VARCHAR(4) PRIMARY KEY,
    TenNganh VARCHAR(100) NOT NULL,
    MaKhoa VARCHAR(2),
    CONSTRAINT fk_nganh_khoa FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa)
);

-- 4. LOP
CREATE TABLE Lop (
    MaLop VARCHAR(11) PRIMARY KEY,
    TenLop VARCHAR(100) NOT NULL UNIQUE,
    MaNganh VARCHAR(4),
    CONSTRAINT fk_lop_nganh FOREIGN KEY (MaNganh) REFERENCES Nganh(MaNganh)
);

-- 5. MON HOC
CREATE TABLE MonHoc (
    MaMH VARCHAR(7) PRIMARY KEY,
    TenMH VARCHAR(100) NOT NULL,
    SoTinChi INT NOT NULL,
    CHECK (SoTinChi > 0)
);

-- 6. QUAN TRI
CREATE TABLE QuanTri (
    MaAdmin INT AUTO_INCREMENT PRIMARY KEY,
    HoTen VARCHAR(100),
    ID_TaiKhoan INT UNIQUE,
    CONSTRAINT fk_admin_taikhoan FOREIGN KEY (ID_TaiKhoan) REFERENCES TaiKhoan(ID_TaiKhoan)
);

-- 7. HO SO XET TUYEN
CREATE TABLE HSO_XETTUYEN (
    MaHSO INT AUTO_INCREMENT PRIMARY KEY,
    ID_TaiKhoan INT UNIQUE,
    HoTen VARCHAR(100) NOT NULL,
    CCCD VARCHAR(12) NOT NULL UNIQUE,
    SDT VARCHAR(15) NOT NULL UNIQUE,
    CONSTRAINT fk_hso_taikhoan FOREIGN KEY (ID_TaiKhoan) REFERENCES TaiKhoan(ID_TaiKhoan)
);

-- 8. SINH VIEN
CREATE TABLE SinhVien (
    MaSV VARCHAR(10) PRIMARY KEY,
    HoTen VARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    ID_TaiKhoan INT UNIQUE,
    MaLop VARCHAR(11),
    MaHSO INT NULL,
    CONSTRAINT fk_sv_taikhoan FOREIGN KEY (ID_TaiKhoan) REFERENCES TaiKhoan(ID_TaiKhoan),
    CONSTRAINT fk_sv_lop FOREIGN KEY (MaLop) REFERENCES Lop(MaLop),
    CONSTRAINT fk_sv_hso FOREIGN KEY (MaHSO) REFERENCES HSO_XETTUYEN(MaHSO)
);

-- 9. PHUONG THUC XET TUYEN
CREATE TABLE PT_XetTuyen (
    MaPTXT VARCHAR(5) PRIMARY KEY,
    MaNganh VARCHAR(4),
    PhuongThuc VARCHAR(100) NOT NULL,
    Diem DECIMAL(4,2) NOT NULL,
    TrangThai ENUM('Chờ duyệt','Trúng tuyển','Từ chối') DEFAULT 'Chờ duyệt',
    MaHSO INT,
    MaAdmin INT NULL,
    CONSTRAINT fk_ptxt_nganh FOREIGN KEY (MaNganh) REFERENCES Nganh(MaNganh),
    CONSTRAINT fk_ptxt_hso FOREIGN KEY (MaHSO) REFERENCES HSO_XETTUYEN(MaHSO),
    CONSTRAINT fk_ptxt_admin FOREIGN KEY (MaAdmin) REFERENCES QuanTri(MaAdmin)
);

-- 10. KET QUA HOC TAP
CREATE TABLE KQ_HocTap (
    MaSV VARCHAR(10),
    MaMH VARCHAR(7),
    Diem DECIMAL(4,2) NOT NULL,
    PRIMARY KEY (MaSV, MaMH),
    CONSTRAINT fk_kq_sv FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV),
    CONSTRAINT fk_kq_mh FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH)
);

-- 11. TOT NGHIEP
CREATE TABLE TotNghiep (
    MaSV VARCHAR(10) PRIMARY KEY,
    GPA DECIMAL(4,2) NOT NULL,
    XepLoai ENUM('Xuất sắc','Giỏi','Khá','Trung bình','Yếu') NOT NULL,
    CHECK (GPA >= 0 AND GPA <= 4.0),
    CONSTRAINT fk_tn_sv FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV)
);

-- 12. THONG BAO
CREATE TABLE ThongBao (
    MaTB INT AUTO_INCREMENT PRIMARY KEY,
    NoiDung VARCHAR(255) NOT NULL,
    NgayGui DATETIME DEFAULT CURRENT_TIMESTAMP,
    MaAdmin INT,
    CONSTRAINT fk_tb_admin FOREIGN KEY (MaAdmin) REFERENCES QuanTri(MaAdmin)
);

-- 13. THONG BAO NGUOI NHAN
CREATE TABLE TB_NguoiNhan (
    MaTBNN INT AUTO_INCREMENT PRIMARY KEY,
    MaTB INT NOT NULL,
    ID_TaiKhoan INT NOT NULL,
    TrangThaiDoc BOOLEAN DEFAULT FALSE,
    ThoiGianDoc DATETIME NULL,
    CONSTRAINT fk_tbnn_tb FOREIGN KEY (MaTB) REFERENCES ThongBao(MaTB),
    CONSTRAINT fk_tbnn_tk FOREIGN KEY (ID_TaiKhoan) REFERENCES TaiKhoan(ID_TaiKhoan)
);

-- 14. VIEC LAM SINH VIEN
CREATE TABLE ViecLamSinhVien (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MaSV VARCHAR(10) NOT NULL,
    TenCongTy VARCHAR(255) NOT NULL,
    ChucVu VARCHAR(100),
    DiaChiCongTy VARCHAR(255),
    ThoiGianBatDau DATE,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_vlsv_sv FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV)
);

-- =============================================
-- SAMPLE DEFAULT ADMIN ACCOUNT
-- =============================================
INSERT INTO TaiKhoan (TenDangNhap, MatKhau, VaiTro)
VALUES ('admin', '123456', 'admin');
